name: chatshat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Horizon
      fonts:
        - asset: fonts/Horizon.ttf
        - asset: fonts/Horizon.otf
  uses-material-design: true

  assets:
    - images/
